// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bio struct {
	ID              string   `json:"id"`
	User            *User    `json:"user"`
	Interests       *string  `json:"interests,omitempty"`
	Age             *int32   `json:"age,omitempty"`
	Gender          *string  `json:"gender,omitempty"`
	Location        *string  `json:"location,omitempty"`
	PreferredRadius *float64 `json:"preferredRadius,omitempty"`
	Info            *string  `json:"info,omitempty"`
}

type Profile struct {
	ID   string `json:"id"`
	User *User  `json:"user"`
}

type Query struct {
}

type User struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Email          string   `json:"email"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Bio            *Bio     `json:"bio,omitempty"`
	Profile        *Profile `json:"profile,omitempty"`
}
